### PR TITLE
Color fix

### PR DESCRIPTION
**Pull request by marremaj**
Removing the gradient library and cleanup of old colors

### CODE REVIEW

**Comment by ahto** [comment]
There are some linting issues. following command fails now:
npm test

One way to quicly fix them is the command:
npm run eslint:fix

**Comment by ahto** [comment]
Screenshot_20210215-103111

I had issues with the bottom fade effect. i think i gave different color to top fade than bottom fade because of the gradient. can you see if this can be fixed now too?

**Comment by ahto** [comment]
Also the reset button in skill filter page was a button but it is now same color as the background.

Should the bg color be different or the button color? idk.

**Comment by ahto** [comment]
Looks good!

**Review by ahto — APPROVED** [review]

**Review by ahto — APPROVED** [review]

**Review by rottabonus — APPROVED** [review]

**Pull request merged**
