### PR TITLE
Replace AlertBox with new "Toast"

### PR DESCRIPTION
**Pull request by rottabonus**
- in scrollview absolute positioned toast wont work, so the toast is wrapped in a transparent Modal
- caveat: UI cannot be used when the toast appears
-  decrease cooldown-period to 3000ms, to make the toast pop-better

### Success toasts in app
https://user-images.githubusercontent.com/34128180/159112554-c594b366-f3b4-4d55-9a85-fbe8e92e8f72.mov

### The only failure toast in app
https://user-images.githubusercontent.com/34128180/159112894-1055d01c-69d1-4c87-92df-07c5d0f9481c.mov

### CODE REVIEW

**Comment by pheis** [comment]
Looks solid!

What is the reasoning behind separate toast props mod?

**Comment by pheis** [comment]
Can't find approve button from GH mobile app :P

**Comment by rottabonus** [comment]
> Looks solid!
> 
> What is the reasoning behind separate toast props mod?

Just I thought the file looked a bit clunky when it was in the component, but not really a strong opinion

**Review by Osamah-learn — COMMENTED** [review]
You are the best Keep gong bro

**Review by ahto — APPROVED** [review]
👍

**Pull request merged**
