### PR TITLE
add border to toggle switch

### PR DESCRIPTION
**Pull request by saarikivit**
The screenshots can be found in ylitse chat in the matrix, ylitse mobile app channel.

### Note
The color: formBorderGray: '#AFBFCD' was added.

### CODE REVIEW

**Review by rottabonus — APPROVED** [review]
Nice

**Comment by saarikivit** [comment]
# Feel free to merge this pull request. It does not have any timing constraints.

**Review by rottabonus — APPROVED** [review]
I see you merged the master into this branch. I don't mind it, but usually we rebase the feature-branch to master, so we move the commits after the master-commits.

**Comment by saarikivit** [comment]
> I see you merged the master into this branch. I don't mind it, but usually we rebase the feature-branch onto master, so we move the commits after the master-commits.

True, I resolved the conflict here in github. It seems to have merged things.

**Comment by saarikivit** [comment]
I wonder, what is the appropriate way to go about this now? @rottabonus

**Comment by rottabonus** [comment]
> I wonder, what is the appropriate way to go about this now? @rottabonus

I think its fine to merge. 

If we want to clean it up, we could drop the merge-commit, then do a rebase onto current master, resolve the conflicts and push the new history here. 

But alas I think it's fine to merge. No need to make it more complicated. =)

**Pull request merged**
