### PR TITLE
Update node

### PR DESCRIPTION
**Pull request by pheis**

### CODE REVIEW

**Comment by rottabonus** [comment]
Affexts deps, so would want to include the updated package.lock.

**Comment by pheis** [comment]
> Affexts deps, so would want to include the updated package.lock.

Does not update for me :P, I'll look into this later.

**Comment by rottabonus** [comment]
Also other thing: 
Need to make sure the builds succees with this node versiokn toi

> > Affexts deps, so would want to include the updated package.lock.
> 
> Does not update for me :P, I'll look into this later.

Oh cool. Also we want to check if the branch builds OK in appcenter

**Comment by rottabonus** [comment]
I'll close this and upgrade node same time as I upgrade the RN version

**Pull request closed without merging**
